### ISSUE TITLE
[Blockchain] Todo

### ISSUE THREAD

**Issue by siraegi** [OHuIShI/Grid-Monopoly#5]
- [x] 게임 로비 당 short id 로 고유 로비id 부여
- [x] p2p.ts 모듈로 만들기 -> 게임 로비 당 하나 생성
- [x] p2p.ts 에서 blockchain.ts 호출하여 블록 생성
- [x] blockchain.ts 에 전체 블록체인 배열 존재

**Comment by siraegi** [comment]
- [ ] 파일로 블록체인 저장
